### ISSUE TITLE
File can not be extracted on win10 with git latest versioin

### ISSUE THREAD

**Issue by c0001** [lujun9972/linux-document#3]
Cause the name format limit of windows like the issue [https://github.com/lujun9972/emacs-document/issues/49](url) .

Hope you fix (or optimize) it for windows user 👍 .

Regards for you
c0001
2018/4/3

**Comment by lujun9972** [comment]
具体哪些文件名有问题呀？能给一下名字么？
另外，其实这个项目已经弃坑了。
现在我加入到 [linuxcn的翻译组](https://github.com/LCTT/TranslateProject)里去了
